export enum ActionName {
  CHANGE_PAGE = 'CHANGE_PAGE',
  CHANGE_PAGE_SIZE = 'CHANGE_PAGE_SIZE',
  CHANGE_ORDER_BY = 'CHANGE_ORDER_BY',
  CHANGE_FILTER = 'CHANGE_FILTER',
  SET_VARIABLES = 'SET_VARIABLES',
  CHANGE_SELECTED = 'CHANGE_SELECTED',
  CHANGE_COMPACT = 'CHANGE_COMPACT',
}
